[package]
name = "Hatchling-Lang-Compiler"
version = "0.1.0"
edition = "2021"
authors = ["Tyler Adam Martinez <tyleradammartinez@outlook.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.83"
